belief_threshold: 0.99
search_genes:
- TOPBP1
- UIMC1
- BABAM2
- ABRAXAS1
- ABRAXAS2
- TP53BP1
- PARPBP
- BRIP1
- FBXO18
- XRCC6
- XRCC5
- RPA1
- PAXIP1
- ERCC1
- ERCC4
- ERCC2
- ERCC3
- ERCC5
- RAD23B
- GTF2H1
- GTF2H2
- GTF2H3
- GTF2H4
- ERCC8
- ERCC6
- POLR2A
- POLR2B
- POLR2C
- POLR2D
- POLR2E
- POLR2F
- POLR2G
- POLR2H
- POLR2I
- POLR2L
- POLR2J
- POLR2J2
- POLR2J3
- POLR2K
- POLD1
- POLD2
- POLD3
- POLD4
- LIG1
- POLQ
- PARP1
- RTEL1
- LIG3
- LIG4
- BRCA1
- CHEK2
- ATM
- RBBP8
- BRIP1
- BABAM1
- BRCC3
- RAD51
- BRCA2
- PALB2
- CHEK1
- ATR
- BARD1
- MDC1
- BLM
- RAD52
- FANCM
- XRCC4
- RNF8
- RNF168
- RAD18
- RNF169
- SIRT6
- RIF1
- SIRT7
- DDX21
- XRCC1
- PCNA
- XPA
- DDB1
- DDB2
search_terms:
- UIMC
- BRE
- FAM175A
- 53BP1
- Abraxas
- Srs2
- FANCJ
- FBH1
- KU70
- KU80
- RPA
- RAP80
- MRN
- PTIP
- XPF
- XPD
- XPB
- XPG
- HR23B
- TFIIH
- CSA
- CSB
- RNA PolII
- POL delta
- DNA ligase I
- Pol theta
- DNA ligase III
- DNA ligase IV
- homologous recombination
- double strand break repair
- S phase checkpoint
- RAD51 strand invasion
- end resection
- non-homologous end joining
- single strand break repair
- nucleotide excision repair
- DNA damage
- DNA repair

